In [1]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

In [2]:
df=pd.read_csv('cars.csv')
df

,Make,Model,CC,Used since,Km,Transmission,City,Color,Body Style,Fuel,...,Alloy wheels,Rear camera,GPS,Fog light,Rear spoiler,Cruise control,Power Seats,Central lock,Alarm,Price
0,Nissan,Sunny,NaN,2015.0,"130,000 Km",automatic,El Haram,Red,Sedan,gas,...,False,False,False,False,False,False,False,False,False,NaN
1,Mercedes,E 350,NaN,2018.0,"33,000 Km",automatic,Cairo,White,Sedan,gas,...,False,False,False,False,False,False,False,False,False,NaN
2,Hyundai,Veloster,NaN,2012.0,"90,000 Km",automatic,Al Shorouk,Red,NaN,gas,...,True,True,True,False,True,False,False,True,False,NaN
3,Seat,Leon,NaN,2017.0,"149,000 Km",automatic,Nasr city,White,NaN,gas,...,True,False,False,False,False,False,False,False,True,NaN
4,Renault,Logan,NaN,2018.0,"89,590 Km",automatic,Kafr el-Sheikh,Light grey,NaN,gas,...,False,False,False,False,False,False,False,False,True,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6718,Chery,Tiggo,1600 CC,2019.0,"60,000 Km",automatic,Cairo,Petroleum,4x4,gas,...,False,False,False,False,False,False,False,True,False,NaN
6719,Chevrolet,Captiva,1600 CC,2021.0,"18,000 Km",automatic,Alexandria,White,4x4,gas,...,True,False,False,False,False,False,False,False,False,NaN
6720,Fiat,131,NaN,1976.0,0 Km,manual,El Marg,Blue,NaN,gas,...,False,False,False,False,False,False,False,False,False,NaN
6721,Daewoo,Nubira 2,1600 CC,2009.0,"200,000 Km",manual,Suez,Silver,Sedan,gas,...,False,False,False,False,False,False,False,True,False,NaN
6722,Skoda,Felicia,NaN,1997.0,"120,000 Km",manual,Shobra,Black,NaN,gas,...,True,False,False,False,False,False,False,False,False,NaN

In [3]:
df.head(5)

,Make,Model,CC,Used since,Km,Transmission,City,Color,Body Style,Fuel,...,Alloy wheels,Rear camera,GPS,Fog light,Rear spoiler,Cruise control,Power Seats,Central lock,Alarm,Price
0,Nissan,Sunny,NaN,2015.0,"130,000 Km",automatic,El Haram,Red,Sedan,gas,...,False,False,False,False,False,False,False,False,False,NaN
1,Mercedes,E 350,NaN,2018.0,"33,000 Km",automatic,Cairo,White,Sedan,gas,...,False,False,False,False,False,False,False,False,False,NaN
2,Hyundai,Veloster,NaN,2012.0,"90,000 Km",automatic,Al Shorouk,Red,NaN,gas,...,True,True,True,False,True,False,False,True,False,NaN
3,Seat,Leon,NaN,2017.0,"149,000 Km",automatic,Nasr city,White,NaN,gas,...,True,False,False,False,False,False,False,False,True,NaN
4,Renault,Logan,NaN,2018.0,"89,590 Km",automatic,Kafr el-Sheikh,Light grey,NaN,gas,...,False,False,False,False,False,False,False,False,True,NaN

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6723 entries, 0 to 6722
Data columns (total 51 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   Make                        6654 non-null   object
 1   Model                       6654 non-null   object
 2   CC                          2052 non-null   object
 3   Used since                  6654 non-null   float64
 4   Km                          6654 non-null   object
 5   Transmission                6654 non-null   object
 6   City                        6654 non-null   object
 7   Color                       6654 non-null   object
 8   Body Style                  2326 non-null   object
 9   Fuel                        6654 non-null   object
 10  Leather seats               6723 non-null   bool
 11  Closing mirrors             6723 non-null   bool
 12  Intelligent parking system  6723 non-null   bool
 13  Sunroof                     6723 non-null   bool
 14  Fabric brushes              6723 non-null   bool
 15  Air Conditioning            6723 non-null   bool
 16  Power Steering              6723 non-null   bool
 17  Remote Keyless              6723 non-null   bool
 18  Electric mirrors            6723 non-null   bool
 19  Front Power Windows         6723 non-null   bool
 20  Back Power Windows          6723 non-null   bool
 21  Tinted Glass                6723 non-null   bool
 22  CD Player                   6723 non-null   bool
 23  DVD Player                  6723 non-null   bool
 24  Bluetooth                   6723 non-null   bool
 25  Multifunction               6723 non-null   bool
 26  Cassette Radio              6723 non-null   bool
 27  AUX                         6723 non-null   bool
 28  CD Changer                  6723 non-null   bool
 29  USB Port                    6723 non-null   bool
 30  Anti - theft System         6723 non-null   bool
 31  Side Airbag                 6723 non-null   bool
 32  ABS                         6723 non-null   bool
 33  EPS                         6723 non-null   bool
 34  EBD                         6723 non-null   bool
 35  ESP                         6723 non-null   bool
 36  Sensors                     6723 non-null   bool
 37  Rear sensors                6723 non-null   bool
 38  Driver Airbag               6723 non-null   bool
 39  Passenger Airbag            6723 non-null   bool
 40  Front sensors               6723 non-null   bool
 41  Alloy wheels                6723 non-null   bool
 42  Rear camera                 6723 non-null   bool
 43  GPS                         6723 non-null   bool
 44  Fog light                   6723 non-null   bool
 45  Rear spoiler                6723 non-null   bool
 46  Cruise control              6723 non-null   bool
 47  Power Seats                 6723 non-null   bool
 48  Central lock                6723 non-null   bool
 49  Alarm                       6723 non-null   bool
 50  Price                       0 non-null      float64
dtypes: bool(40), float64(2), object(9)
memory usage: 840.5+ KB

In [5]:
df.isna().sum()

Make                            69
Model                           69
CC                            4671
Used since                      69
Km                              69
Transmission                    69
City                            69
Color                           69
Body Style                    4397
Fuel                            69
Leather seats                    0
Closing mirrors                  0
Intelligent parking system       0
Sunroof                          0
Fabric brushes                   0
Air Conditioning                 0
Power Steering                   0
Remote Keyless                   0
Electric mirrors                 0
Front Power Windows              0
Back Power Windows               0
Tinted Glass                     0
CD Player                        0
DVD Player                       0
Bluetooth                        0
Multifunction                    0
Cassette Radio                   0
AUX                              0
CD Changer                       0
USB Port                         0
Anti - theft System              0
Side Airbag                      0
ABS                              0
EPS                              0
EBD                              0
ESP                              0
Sensors                          0
Rear sensors                     0
Driver Airbag                    0
Passenger Airbag                 0
Front sensors                    0
Alloy wheels                     0
Rear camera                      0
GPS                              0
Fog light                        0
Rear spoiler                     0
Cruise control                   0
Power Seats                      0
Central lock                     0
Alarm                            0
Price                         6723
dtype: int64